#!/bin/sh
############################################################
#             Habitat Wiki Installation Scripts
#
#  postrm: post-uninstallation script for deb package
#
#  Author: Qianqian Fang <fangq at nmr.mgh.harvard.edu>
#  History:
#      2009/05/26    Initial version
#  
#  Macro %NAME% and %VERSION% must be replaced before running
#
###########################################################

NAME=%NAME%
PREFIX=/var/lib
