#!/usr/bin/env perl
# HMAC-signed CSRF tokens generated by GetFormStart and verified by
# CSRFCheckOrDie at the top of every state-changing handler.

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use Test::More;
use HabitatHarness;

HabitatHarness::load_wiki();
HabitatHarness::set_test_secret();
HabitatHarness::freeze_time(1_700_000_000);

# ----------------------------------------------------------------
# Round-trip
# ----------------------------------------------------------------
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1001;
    my $tok = HabitatEngine::GenCSRFToken();
    like( $tok, qr/\A\d+\|[0-9a-f]{64}\z/, "token shape: <exp>|<64-hex sig>" );
    is( HabitatEngine::VerifyCSRFToken($tok), 1, "fresh token verifies" );

    my ($exp) = split /\|/, $tok;
    is( $exp, 1_700_000_000 + 86400, "default TTL is 24h" );
}

# Rejection cases
is( HabitatEngine::VerifyCSRFToken(undef), 0, "undef rejected" );
is( HabitatEngine::VerifyCSRFToken(""),    0, "empty rejected" );
is( HabitatEngine::VerifyCSRFToken("xx"),  0, "garbage rejected" );
is( HabitatEngine::VerifyCSRFToken( {} ),  0, "ref rejected" );

# ----------------------------------------------------------------
# Tampering
# ----------------------------------------------------------------
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1001;
    my $tok = HabitatEngine::GenCSRFToken();

    # Signature tampering
    my $bad_sig = $tok;
    substr( $bad_sig, -1 ) = ( substr( $bad_sig, -1 ) eq 'a' ) ? 'b' : 'a';
    is( HabitatEngine::VerifyCSRFToken($bad_sig), 0, "signature tampering invalidates" );

    # Expiry tampering -- changes the signed content
    my ( $exp, $sig ) = split /\|/, $tok;
    is( HabitatEngine::VerifyCSRFToken( ( $exp + 1 ) . "|$sig" ),
        0, "expiry tampering invalidates" );
}

# ----------------------------------------------------------------
# Binding to UserID — a token issued to user A is unusable as user B
# ----------------------------------------------------------------
my $tok_alice;
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1001;
    $tok_alice = HabitatEngine::GenCSRFToken();
    is( HabitatEngine::VerifyCSRFToken($tok_alice), 1, "alice can verify alice's token" );
}
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1002;
    is( HabitatEngine::VerifyCSRFToken($tok_alice),
        0, "bob cannot verify alice's token (uid bound into signature)" );
}

# ----------------------------------------------------------------
# Expiry
# ----------------------------------------------------------------
my $tok_with_known_exp;
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1001;
    $tok_with_known_exp = HabitatEngine::GenCSRFToken();
}
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1001;
    HabitatHarness::freeze_time( 1_700_000_000 + 86399 );
    is( HabitatEngine::VerifyCSRFToken($tok_with_known_exp), 1,
        "token valid 1s before 24h expiry" );

    HabitatHarness::freeze_time( 1_700_000_000 + 86401 );
    is( HabitatEngine::VerifyCSRFToken($tok_with_known_exp),
        0, "token rejected 1s after 24h expiry" );
}
HabitatHarness::freeze_time(1_700_000_000);

# ----------------------------------------------------------------
# Anonymous users get CSRF protection too (uid 111 / 113 etc.)
# Same uid at form-render and submit => verifies. Different => fails.
# ----------------------------------------------------------------
my $anon_tok;
{
    no warnings 'once';
    local $HabitatEngine::UserID = 111;    # anonymous
    $anon_tok = HabitatEngine::GenCSRFToken();
    is( HabitatEngine::VerifyCSRFToken($anon_tok),
        1, "anonymous uid (111) can issue and verify its own token" );
}
{
    no warnings 'once';
    local $HabitatEngine::UserID = 111;
    is( HabitatEngine::VerifyCSRFToken($anon_tok),
        1, "anonymous tokens are consistent across the anon session" );
}

# ----------------------------------------------------------------
# Secret rotation invalidates outstanding CSRF tokens
# ----------------------------------------------------------------
my $tok_rotate;
{
    no warnings 'once';
    local $HabitatEngine::UserID = 1001;
    $tok_rotate = HabitatEngine::GenCSRFToken();
}
{
    no warnings 'once';
    local $HabitatEngine::SiteSecret = "rotated" x 10;
    local $HabitatEngine::UserID     = 1001;
    is( HabitatEngine::VerifyCSRFToken($tok_rotate),
        0, "rotating site secret invalidates outstanding CSRF tokens" );
}

done_testing;
